<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-14T22:44:36 IST" name="Suite" finished-at="2024-11-14T22:44:50 IST" duration-ms="14485">
    <groups>
    </groups>
    <test started-at="2024-11-14T22:44:36 IST" name="Test" finished-at="2024-11-14T22:44:50 IST" duration-ms="14485">
      <class name="com.ect.testcases.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.ect.testcases.LoginTest@534ca02b]" started-at="2024-11-14T22:44:36 IST" name="setup" finished-at="2024-11-14T22:44:43 IST" duration-ms="6827" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verify(java.lang.String,java.lang.String)[pri:0, instance:com.ect.testcases.LoginTest@534ca02b]" started-at="2024-11-14T22:44:44 IST" name="verify" data-provider="logindataProvider" finished-at="2024-11-14T22:44:49 IST" duration-ms="4628" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[ravi@dhiyotech.in]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Demo]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify -->
        <test-method signature="verify(java.lang.String,java.lang.String)[pri:0, instance:com.ect.testcases.LoginTest@534ca02b]" started-at="2024-11-14T22:44:49 IST" name="verify" data-provider="logindataProvider" finished-at="2024-11-14T22:44:50 IST" duration-ms="1711" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[infotek@solutions.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Demo12]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.ect.testcases.LoginTest.verify(LoginTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify -->
      </class> <!-- com.ect.testcases.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
